### PR TITLE
Added an option to insert a link to a card

### PR DESCRIPTION
**Pull request by martisak**
I have added a menu item to insert a link to a card at the current cursor location. 

## Future work
* Format of link should be configurable or depend on current file (wiki, html, ..)

Thanks for a great plugin!

### CODE REVIEW

**Comment by NicoSantangelo** [comment]
Really cool!

I agree on basing the link format on the file type, but for the time being I think adding it without the surrounding brackets is a safer bet. That is `https://trello.com/c/JEGZ6zkw/1-card` instead of `[[https://trello.com/c/JEGZ6zkw/1-card]]`.

What do you think?

**Comment by martisak** [comment]
Makes total sense :). 

Question: Would it be possible to use the [shortUrl](https://developers.trello.com/reference#card-object) instead of the long [url](https://developers.trello.com/reference#card-object) field? The links can be pretty long ...

**Comment by NicoSantangelo** [comment]
Yeah I agree. For it to work, you'll have to add a `Field` to the `Card` class on `Trello/lib/trollop/lib.py`. Something like:

```python
short_url = Field('shortUrl')
```

**Comment by martisak** [comment]
OK, so I removed the brackets, added the shorturl field and changed the link so that it is short.

**Comment by NicoSantangelo** [comment]
Perfect!
Just a tiny request, can we change `shortUrl` for `shorturl` or `short_url` to keep the underscore convention?

I can merge this as is and change it myself pre-release but I don't want to rewrite your code (:

**Comment by martisak** [comment]
Done :)

**Comment by nicosantangelo** [comment]
Thanks a lot!
I'll create a release right away

**Pull request merged**
